version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    labels:
      com.obsidian.host: "${COM_GABBRO_HOST}"
      com.obsidian.service: "portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-data:/data
    networks:
      - nginx
    environment:
      VIRTUAL_HOST: "portainer.${COM_GABBRO_DOMAIN}"
      VIRTUAL_PORT: 9000
  gitlab-runner-1:
    build:
      context: ./gitlab-runner
    container_name: gitlab-runner-1
    labels:
      com.obsidian.host: "${COM_GABBRO_HOST}"
      com.obsidian.service: "gitlab-runner-1"
    group_add:
      - "${COM_GABBRO_PGID}"
    environment:
      COM_GABBRO_INFISICAL_HOST: "infisical"
      COM_GABBRO_DNS_HOST: "${COM_GABBRO_DNS_HOST}"
    volumes:
      - gitlab-runner-1-data:/etc/gitlab-runner/
      - ./gitlab-runner/config-1.toml:/etc/gitlab-runner/config.toml
    networks:
      - infisical
  gitlab-runner-2:
    build:
      context: ./gitlab-runner
    container_name: gitlab-runner-2
    labels:
      com.obsidian.host: "${COM_GABBRO_HOST}"
      com.obsidian.service: "gitlab-runner-2"
    group_add:
      - "${COM_GABBRO_PGID}"
    environment:
      COM_GABBRO_INFISICAL_HOST: "infisical"
      COM_GABBRO_DNS_HOST: "${COM_GABBRO_DNS_HOST}"
    volumes:
      - gitlab-runner-2-data:/etc/gitlab-runner/
      - ./gitlab-runner/config-2.toml:/etc/gitlab-runner/config.toml
    networks:
      - infisical
  infisical:
    image: infisical/infisical:latest
    container_name: infisical
    labels:
      com.obsidian.host: "${COM_GABBRO_HOST}"
      com.obsidian.service: "infisical"
    environment:
      ENCRYPTION_KEY: "${COM_GABBRO_INFISICAL_ENCRYPTION_KEY}"
      JWT_SIGNUP_SECRET: "${COM_GABBRO_INFISICAL_JWT_SIGNUP_SECRET}"
      JWT_REFRESH_SECRET: "${COM_GABBRO_INFISICAL_JWT_REFRESH_SECRET}"
      JWT_AUTH_SECRET: "${COM_GABBRO_INFISICAL_JWT_AUTH_SECRET}"
      JWT_MFA_SECRET: "${COM_GABBRO_INFISICAL_JWT_MFA_SECRET}"
      JWT_SERVICE_SECRET: "${COM_GABBRO_INFISICAL_JWT_SERVICE_SECRET}"
      HTTPS_ENABLED: false
      MONGO_URL: "mongodb://${COM_GABBRO_MONGO_USERNAME}:${COM_GABBRO_MONGO_PASSWORD}@infisical-mongo:27017/?authSource=admin"
      VIRTUAL_HOST: "infisical.${COM_GABBRO_DOMAIN}"
      VIRTUAL_PORT: 80
    networks:
      - infisical
  infisical-mongo:
    container_name: infisical-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${COM_GABBRO_MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${COM_GABBRO_MONGO_PASSWORD}"
    volumes:
      - infisical-mongo-data:/data/db
    networks:
      - infisical
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx
      - infisical
volumes:
  gitlab-runner-1-data:
  gitlab-runner-2-data:
  portainer-data:
  infisical-mongo-data:
networks:
  infisical:
  nginx:
