services:
  gabbro-secret-manager:
    image: registry.gitlab.com/haondt/cicd/registry/gabbro-secret-manager:1.1.1
    container_name: gabbro-secret-manager
    networks:
      - gabbro-secret-manager
      - nginx
    depends_on:
      - gabbro-secret-manager-postgres
    environment:
      JweSettings__EncryptionKey: "{{ GSM_ENCRYPTION_KEY }}"
      JweSettings__SigningKey: "{{ GSM_SIGNING_KEY }}"
      PersistenceSettings__Driver: postgres
      PostgreSQLSettings__ConnectionString: "host=gabbro-secret-manager-postgres;Username=gsm;Password={{ GSM_POSTGRES_PASSWORD }};Database=gsm"
      AuthenticationSettings__UseSecureCookies: false
      VIRTUAL_HOST: "gsm.flint"
      VITRUAL_PORT: 8080
  gabbro-secret-manager-postgres:
    image: postgres
    networks:
      - gabbro-secret-manager
    volumes:
      - gabbro-secret-manager-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gsm
      POSTGRES_PASSWORD: "{{ GSM_POSTGRES_PASSWORD }}"
    shm_size: 128mb
networks:
  gabbro-secret-manager:
volumes:
  gabbro-secret-manager-data:
